# Generated by Django 4.1.7 on 2023-04-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_sql_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
