# Generated by Django 4.1.7 on 2023-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_sql_app', '0002_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(max_length=50)),
                ('fio', models.CharField(blank=True, db_column='FIO', max_length=100, null=True)),
                ('ntab', models.CharField(blank=True, max_length=10, null=True)),
                ('amcom', models.DecimalField(blank=True, db_column='AMCOM', decimal_places=2, max_digits=10, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
                ('fcard', models.IntegerField(blank=True, null=True)),
                ('ncard', models.IntegerField(blank=True, null=True)),
                ('rowver', models.BinaryField(blank=True, max_length='max', null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=36, null=True)),
                ('vid', models.IntegerField(db_column='Vid')),
                ('kolall', models.IntegerField(blank=True, db_column='KolAll', null=True)),
                ('kol', models.IntegerField(blank=True, db_column='Kol', null=True)),
            ],
            options={
                'db_table': 'CARDS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('ntab', models.CharField(max_length=10)),
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amcom', models.DecimalField(blank=True, db_column='AMCOM', decimal_places=2, max_digits=10, null=True)),
                ('kassid', models.IntegerField(blank=True, null=True)),
                ('sum_gp', models.DecimalField(blank=True, db_column='SUM_GP', decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='DATE', null=True)),
                ('iactive', models.SmallIntegerField(blank=True, db_column='IACTIVE', null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=36, null=True)),
                ('fcard', models.IntegerField(blank=True, null=True)),
                ('ncard', models.IntegerField(blank=True, null=True)),
                ('vid', models.IntegerField(blank=True, db_column='Vid', null=True)),
                ('kol', models.IntegerField(blank=True, db_column='Kol', null=True)),
            ],
            options={
                'db_table': 'SALE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(db_column='Vid')),
                ('name', models.CharField(max_length=25)),
                ('use_kol', models.SmallIntegerField(blank=True, db_column='Use_Kol', null=True)),
            ],
            options={
                'db_table': 'Talon',
                'managed': False,
            },
        ),
    ]
